In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr[0], arr[1], arr[2])
arr[2] = 4
print(arr)

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2.shape)
print(arr2[0,0], arr2[0,1], arr2[1,0])
print(arr2[-1])

<class 'numpy.ndarray'>
int32
(3,)
1 2 3
[1 2 4]
(2, 3)
1 2 4
[4 5 6]


In [3]:
zero = np.zeros((2, 2))
print(zero)

one = np.ones((1, 2))
print(one)

constant = np.full((2, 2), 5)
print(constant)

diag = np.eye(3)
print(diag)

diag = np.eye(4, k=1)
print(diag)

rand = np.random.random((2, 2))
print(rand)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.74279883 0.02695154]
 [0.53775093 0.73655491]]


In [4]:
arr = np.arange(10)
print(arr[0:8:2])

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[:2, :2])

[0 2 4 6]
[[1 2]
 [5 6]]


In [5]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr[[0, 1, 2], [0, 1, 1]])

[1 4 6]


In [6]:
arr = np.arange(9)
reshape_arr = arr.reshape(3, 3)
print(reshape_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
arr = np.arange(8).reshape(2, 4)

#print(arr[4])

print(arr.flat[4])

4


In [8]:
arr = np.arange(8).reshape(2, 4)

print(arr.flatten())

[0 1 2 3 4 5 6 7]


In [9]:
arr = np.arange(8).reshape(2, 4)

print(arr.transpose())

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [10]:
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])
c = a + b
print(c)

bc = np.broadcast(a, b)
x = np.zeros(bc.shape)

x.flat = [a + b for (a,b) in bc]
print(x)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_resized = np.resize(arr, [3, 3])
print(arr_resized)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [12]:
unique = np.unique([1, 1, 2, 2, 3, 3])
print(unique)

arr = np.array([[1, 1], [2, 3]])
print(np.unique(arr))

arr = np.array(['a', 'b', 'b', 'c', 'a'])
unique, indices = np.unique(arr, return_index=True)
print(unique, indices)

count = np.unique(arr, return_counts=True)
print(count[0], count[1])

[1 2 3]
[1 2 3]
['a' 'b' 'c'] [0 1 3]
['a' 'b' 'c'] [2 2 1]
